---

#
# Installs and configures the New Relic Infrastructure agent
#
- name: Confirm RedHat lsb util is present
  yum: name=redhat-lsb-core state=present
  when: os_name|lower == 'redhat'

- name: Reread ansible_lsb facts
  setup: filter=ansible_lsb*
  when: os_name|lower == 'redhat'

- name: setup agent repo keys
  apt_key:
    url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present
  when: os_name|lower == 'debian'

- name: setup agent repo keys
  rpm_key:
    key: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present
  when: os_name|lower == 'redhat'

- name: Confirm Debian apt-transport-https is present
  apt: name=apt-transport-https state=present
  when: os_name|lower == 'debian'

- name: setup agent repo reference
  apt_repository:
    repo: "deb https://download.newrelic.com/infrastructure_agent/linux/apt {{ os_codename }} main"
    state: present
  when: os_name|lower == 'debian'

- name: setup agent repo reference
  yum_repository:
    baseurl: "https://download.newrelic.com/infrastructure_agent/linux/yum/el/{{ os_version }}/x86_64"
    gpgcheck: yes
    gpgkey: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    name: 'New-Relic-Infrastructure'
    repo_gpgcheck: yes
    state: present
    description: New Relic Infrastructure
  when: os_name|lower == 'redhat'

- name: install agent
  yum:
    name: "newrelic-infra{{ agent_version }}"
    state: "{{ agent_state }}"
  when: os_name|lower == 'redhat'

- name: install agent
  apt:
    name: "newrelic-infra{{ agent_version }}"
    state: "{{ agent_state }}"
    update_cache: yes
  when: os_name|lower == 'debian'

- name: setup agent config
  template: src=newrelic-infra.yml.j2 dest=/etc/newrelic-infra.yml
  notify: restart newrelic-infra
  when: agent_state != "absent"

- name: setup agent service
  service: name=newrelic-infra state=started enabled=yes
  when: agent_state != "absent"
